name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # List directories containing Dockerfiles
    - name: List Dockerfile directories
      run: |
        echo "::set-output name=dockerfile-dirs::$(find . -type f -name 'Dockerfile' -exec dirname {} \; | sort -u)"

    # Build Docker images in each directory
    - name: Build Docker images
      run: |
        for dir in ${{ steps.list-dockerfile-dirs.outputs.dockerfile-dirs }}; do
          ls $dir
          docker build -t my-golang-app:$dir $dir
        done

 #   - name: Log in to Docker Hub
 #     uses: docker/login-action@v1
 #     with:
 #       username: ${{ secrets.DOCKER_USERNAME }}
 #       password: ${{ secrets.DOCKER_PASSWORD }}

 #   # Push Docker images to the registry
 #   - name: Push Docker images to registry
 #     run: |
 #       for dir in ${{ steps.list-dockerfile-dirs.outputs.dockerfile-dirs }}; do
 #         docker push my-golang-app:$dir
 #       done
