name: Go Tests

on:
  push:
    paths:
      - 'cmd/**' # Trigger only when changes occur in the cmd folder and its subfolders
  pull_request:
    paths:
      - 'cmd/**' # Trigger only when changes occur in the cmd folder and its subfolders

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.x' # Set the Go version you want to use

      - name: List changed directories
        id: list_dirs
        run: |
          changed_dirs=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} -- cmd/ | xargs -I{} dirname {})
          echo "::set-output name=changed_dirs::${changed_dirs}"

      - name: Run tests in changed directories
        run: |
          for dir in ${{ steps.list_dirs.outputs.changed_dirs }}; do
            echo "Running tests in $dir"
            cd "$dir" && go test
          done
